-- LedgerKit reads and writes through its authenticated Next.js server routes.
-- No table is exposed directly through Supabase's public Data API.
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "adjustments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "expenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "instruments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "merchants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payment_apps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "people" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refunds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reward_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "transfers" ENABLE ROW LEVEL SECURITY;
